### ISSUE TITLE
Doesn't work with FastAPI / Starlette

### ISSUE THREAD

**Issue by euanrae-gousto** [mikeckennedy/jinja_partials#10]
I've tried to get this running as per the guide using FastAPI / Starlette, and am getting the following error:

<details>
    <summary>Full Stack Trace</summary>
   Stack Trace:

  ```{"name": "courier_management", "timestamp": "2024-04-19T13:02:14.974244", "log_level": "ERROR", "message": "Error: 'render_partial' is undefined URL: http://127.0.0.1:8080/services/create", "source": "[PATH_TO_PROJECT]src/courier_management/web/app.py:72", "involves": ["'render_partial' is undefined", "http://127.0.0.1:8080/services/create"]}
INFO:     127.0.0.1:62525 - "GET /services/create HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "[PATH_TO_PROJECT].venv/lib/python3.8/site-packages/uvicorn/protocols/http/h11_impl.py", line 407, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "[PATH_TO_PROJECT].venv/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 69, in __call__
    return await self.app(scope, receive, send)
  File "[PATH_TO_PROJECT].venv/lib/python3.8/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "[PATH_TO_PROJECT].venv/lib/python3.8/site-packages/starlette/applications.py", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
  File "[PATH_TO_PROJECT].venv/lib/python3.8/site-packages/starlette/middleware/errors.py", line 186, in __call__
    raise exc
  File "[PATH_TO_PROJECT].venv/lib/python3.8/site-packages/starlette/middleware/errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "[PATH_TO_PROJECT].venv/lib/python3.8/site-packages/starlette/middleware/exceptions.py", line 65, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "[PATH_TO_PROJECT].venv/lib/python3.8/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "[PATH_TO_PROJECT].venv/lib/python3.8/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "[PATH_TO_PROJECT].venv/lib/python3.8/site-packages/starlette/routing.py", line 756, in __call__
    await self.middleware_stack(scope, receive, send)
  File "[PATH_TO_PROJECT].venv/lib/python3.8/site-packages/starlette/routing.py", line 776, in app
    await route.handle(scope, receive, send)
  File "[PATH_TO_PROJECT].venv/lib/python3.8/site-packages/starlette/routing.py", line 297, in handle
    await self.app(scope, receive, send)
  File "[PATH_TO_PROJECT].venv/lib/python3.8/site-packages/starlette/routing.py", line 77, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "[PATH_TO_PROJECT].venv/lib/python3.8/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "[PATH_TO_PROJECT].venv/lib/python3.8/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "[PATH_TO_PROJECT].venv/lib/python3.8/site-packages/starlette/routing.py", line 72, in app
    response = await func(request)
  File "[PATH_TO_PROJECT].venv/lib/python3.8/site-packages/fastapi/routing.py", line 278, in app
    raw_response = await run_endpoint_function(
  File "[PATH_TO_PROJECT].venv/lib/python3.8/site-packages/fastapi/routing.py", line 191, in run_endpoint_function
    return await dependant.call(**values)
  File "[PATH_TO_PROJECT]src/courier_management/web/middleware/http.py", line 26, in wrapper
    return _build_template_response(result, env)
  File "[PATH_TO_PROJECT]src/courier_management/web/middleware/http.py", line 34, in _build_template_response
    return TEMPLATES.TemplateResponse(
  File "[PATH_TO_PROJECT].venv/lib/python3.8/site-packages/starlette/templating.py", line 230, in TemplateResponse
    return _TemplateResponse(
  File "[PATH_TO_PROJECT].venv/lib/python3.8/site-packages/starlette/templating.py", line 40, in __init__
    content = template.render(context)
  File "[PATH_TO_PROJECT].venv/lib/python3.8/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "[PATH_TO_PROJECT].venv/lib/python3.8/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "[PATH_TO_PROJECT]src/courier_management/web/templates/services/create_edit_service.html.j2", line 1, in top-level template code
    {% extends "shared/base.html.j2" %}
  File "[PATH_TO_PROJECT]src/courier_management/web/templates/shared/base.html.j2", line 28, in top-level template code
    {% block content %}{% endblock %}
  File "[PATH_TO_PROJECT]src/courier_management/web/templates/services/create_edit_service.html.j2", line 11, in block 'content'
    {{ render_partial("services/partials/create_edit_service_form.j2") }}
  File "[PATH_TO_PROJECT].venv/lib/python3.8/site-packages/jinja2/utils.py", line 83, in from_obj
    if hasattr(obj, "jinja_pass_arg"):
jinja2.exceptions.UndefinedError: 'render_partial' is undefined
```
</details>

The implementation is pretty much as per the docs:
<details>
  <summary>Python</summary>
  Python Code:

  ```
import itertools
from dataclasses import dataclass
from pathlib import Path
from typing import List, Set, Dict

from fastapi import FastAPI, Request, Response, status
from fastapi.responses import HTMLResponse

from mangum import Mangum
from sqlalchemy.orm import Session
from sqlalchemy.sql import text
from starlette.staticfiles import StaticFiles
from starlette.templating import Jinja2Templates
import jinja_partials

# Other Internal imports

APP = FastAPI()
APP.include_router(services_router)
LAMBDA_HANDLER = Mangum(APP)


PARENT_PATH = Path(__file__).parent
TEMPLATES = Jinja2Templates(directory=PARENT_PATH / "templates")
jinja_partials.register_starlette_extensions(TEMPLATES)

# FastAPI routes start here
```
</details>

Jinja Template
<details>
  <summary>Jinja Template</summary>
  Template:

  ```
{% extends "shared/base.html.j2" %}
{% block title %}Courier Service Caps{% endblock %}
{% block content %}

<div class="row">
    <div class="col-md-8">
      <h1>Create / Edit Courier Services</h1>
    </div>
</div>
<div class="row" id="create-courier-service">
    {{ render_partial("services/partials/create_edit_service_form.j2") }}

</div>

{% endblock %}
```

</details>

Is there anything that's obviously missing? It seems that when the template is trying to render, it's 'forgotten' about the `render_partial` function in the environment

**Comment by euanrae-gousto** [comment]
Apologies, my mistake - it was an implementation detail

**Comment by mikeckennedy** [comment]
Glad you caught it.
